"""Create usertable

Revision ID: 12f3afc79eea
Revises: 6e67b8a77e1f
Create Date: 2023-11-10 17:39:22.410772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f3afc79eea'
down_revision = '6e67b8a77e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
