"""Inventory bud-fix

Revision ID: 166b24614109
Revises: 35ea4d0ce7e4
Create Date: 2023-11-28 16:19:24.334258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166b24614109'
down_revision = '35ea4d0ce7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
