"""Inventory bud-fix

Revision ID: 18830362125e
Revises: c752cf8a4983
Create Date: 2023-11-28 15:49:53.331826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18830362125e'
down_revision = 'c752cf8a4983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
