"""Inventory bud-fix

Revision ID: 35ea4d0ce7e4
Revises: 54cadfbaf14f
Create Date: 2023-11-28 16:09:40.110626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ea4d0ce7e4'
down_revision = '54cadfbaf14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
