"""Inventory bud-fix

Revision ID: 40ff932559d4
Revises: 178a0b6d74eb
Create Date: 2023-11-28 16:33:46.092880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ff932559d4'
down_revision = '178a0b6d74eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
