"""Inventory bud-fix

Revision ID: 54cadfbaf14f
Revises: b5d5025f6cbd
Create Date: 2023-11-28 16:03:29.169840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cadfbaf14f'
down_revision = 'b5d5025f6cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
