"""Create sequences

Revision ID: 661458f5529f
Revises: 8724b71bf352
Create Date: 2023-11-16 15:41:13.870901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661458f5529f'
down_revision = '8724b71bf352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
