"""Inventory bud-fix

Revision ID: 929b559d5923
Revises: 166b24614109
Create Date: 2023-11-28 16:23:47.634800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929b559d5923'
down_revision = '166b24614109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('in_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'in_stock')
    # ### end Alembic commands ###
