"""Inventory bud-fix

Revision ID: b5d5025f6cbd
Revises: bc9d09d9d26a
Create Date: 2023-11-28 16:01:40.760518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d5025f6cbd'
down_revision = 'bc9d09d9d26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
