"""Inventory bud-fix

Revision ID: bc9d09d9d26a
Revises: 18830362125e
Create Date: 2023-11-28 15:52:54.768701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9d09d9d26a'
down_revision = '18830362125e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
