"""Create sequences

Revision ID: c59c093de5c9
Revises: 661458f5529f
Create Date: 2023-11-16 15:43:03.675532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59c093de5c9'
down_revision = '661458f5529f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
