"""User table clean up

Revision ID: c752cf8a4983
Revises: c59c093de5c9
Create Date: 2023-11-28 15:27:29.871131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c752cf8a4983'
down_revision = 'c59c093de5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
